mysite/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "main"
urlpatterns = [
    path('', views.index, name="index"),
    path('result/', views.result, name="result")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

mysite/main/models.py
from django.db import models

# Create your models here.

mysite/main/views.py
from django.shortcuts import render, HttpResponse
from . import helpers
import copy

def index(request):
    return render(request, 'main/index.html')

def result(request):
    s = request.POST.get('text')    
    pre1 = helpers.sentence_classification(s)    
    noun = helpers.noun_extraction(pre1)    
    TF, TF_head = helpers.cal_TF(noun)             
    temp_TF = copy.deepcopy(TF)
    TF_IDF = helpers.cal_TF_IDF(noun, temp_TF, TF_head)
    cos = helpers.cosine_sim(TF) 
    jac = helpers.jaccard(TF)
    Euc = helpers.Euclidean(TF)
    man = helpers.manhattan(TF)

    print_TF = []
    for i in TF:
        print_TF.append(i[0:31])
    print_TF_IDF = []
    for i in TF:
        print_TF_IDF.append(i[0:31])
    return render(request, 'main/result.html', {"TF":print_TF, "TF_head":TF_head[0:31], "TF_IDF":print_TF_IDF, "cos":cos, "jac":jac, "Euc":Euc, "man":man})    

mysite/main/templates/main/index.html
<h2>텍스트 분석</h2>

<form action="{% url 'main:result' %}" method="post">
    {% csrf_token %}           
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        
    <textarea cols="50" rows="10" name="text" id="text" value="test">텍스트 전처리는 풀고자 하는 문제의 용도에 맞게 텍스트를 사전에 처리하는 작업입니다. 요리를 할 때 재료를 제대로 손질하지 않으면, 요리가 엉망이 되는 것처럼 텍스트에 제대로 전처리를 하지 않으면 뒤에서 배울 자연어 처리 기법들이 제대로 동작하지 않습니다. 이번 챕터에서는 텍스트를 위한 다양한 전처리 방법들에 대해서 다룹니다.</textarea>
    <p></p>
    <input type="submit" value="제출">
</form>

mysite/main/templates/main/result.html
<h2>텍스트 분석</h2>

디자인 도와주실 분?

<table
    border="1"
    width="50%"
    height="200"
    cellspacing="5">
    <caption>TF(Term Frequency) 계산</caption>
    <thead>
        <tr align="center" bgcolor="white">
            <td>No</td>
            {% for word in TF_head %}
                <th>{{word}}</th>
            {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% for noun in TF %}
        <tr align="center" bgcolor="white">
            <td>문장 {{forloop.counter}}</td>
            {% for word in noun %}
                <td>{{word}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<br>
<br>

<table
    border="1"
    width="50%"
    height="200"
    cellspacing="5">
    <caption>TF-IDF(Term Frequency-Inverse Document Frequency) 계산</caption>
    <thead>
        <tr align="center" bgcolor="white">
            <td>No</td>
            {% for word in TF_head %}
                <th>{{word}}</th>
            {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% for noun in TF_IDF %}
        <tr align="center" bgcolor="white">
            <td>문장 {{forloop.counter}}</td>
            {% for word in noun %}
                <td>{{word}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<br>
<br>

<table
    border="1"
    width="50%"
    height="200"
    cellspacing="5">
    <caption>코사인 유사도</caption>
    <thead>
        <tr align="center" bgcolor="white">
            <td>No</td>
            {% for word in cos %}
                <th>문장 {{forloop.counter}}</th>
            {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% for noun in cos %}
        <tr align="center" bgcolor="white">
            <td>문장 {{forloop.counter}}</td>
            {% for word in noun %}
                <td>{{word}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<br>
<br>

<table
    border="1"
    width="50%"
    height="200"
    cellspacing="5">
    <caption>자카드 유사도</caption>
    <thead>
        <tr align="center" bgcolor="white">
            <td>No</td>
            {% for word in jac %}
                <th>문장 {{forloop.counter}}</th>
            {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% for noun in jac %}
        <tr align="center" bgcolor="white">
            <td>문장 {{forloop.counter}}</td>
            {% for word in noun %}
                <td>{{word}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<br>
<br>

<table
    border="1"
    width="50%"
    height="200"
    cellspacing="5">
    <caption>유클리드 유사도</caption>
    <thead>
        <tr align="center" bgcolor="white">
            <td>No</td>
            {% for word in Euc %}
                <th>문장 {{forloop.counter}}</th>
            {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% for noun in Euc %}
        <tr align="center" bgcolor="white">
            <td>문장 {{forloop.counter}}</td>
            {% for word in noun %}
                <td>{{word}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<br>
<br>

<table
    border="1"
    width="50%"
    height="200"
    cellspacing="5">
    <caption>맨하탄 유사도</caption>
    <thead>
        <tr align="center" bgcolor="white">
            <td>No</td>
            {% for word in man %}
                <th>문장 {{forloop.counter}}</th>
            {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% for noun in man %}
        <tr align="center" bgcolor="white">
            <td>문장 {{forloop.counter}}</td>
            {% for word in noun %}
                <td>{{word}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>